name: Pipeline

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main" ]

env:
  ARTIFACT_JAR_NAME: jar
  ARTIFACT_REPORT_NAME: report

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Check Java Version
        run: java --version

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Application
        run: mvn clean verify site

      - name: Junit Test Dashboard
        uses: janisz/action@v2
        with:
          paths: "target/surefire-reports/TEST-*.xml"

      - name: Test Report
        uses:  dorny/test-reporter@v1
        with:
          name: JUnit Tests
          path: "target/surefire-reports/TEST-*.xml"
          reporter: java-junit

      - name: Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: target/site/jacoco/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.ARTIFACT_JAR_NAME }}
          path: ./target/*.jar

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.ARTIFACT_REPORT_NAME }}
          path: ./target/site